baseURL = "https://weblog.shuuji3.xyz/"
languageCode = "en-us"
title = "Weblog by shuuji3"
# theme
theme = "hugo-now"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Happy Software Engineering"
  author = "TAKAHASHI Shuuji <shuuji3@gmail.com>"
  keywords = ["software-engineering"]
  avatar = "/images/emoji-google-unicorn-face.png"
  displayauthor = false
  # pagination
  paginate = 10
  paginatePath = "page"

[author]
name = "TAKAHASHI Shuuji"
email = "shuuji3@gmail.com"

[markup]
  [markup.highlight]
    noClasses = true
    style = "github"
