baseURL = "https://weblog.shuuji3.xyz/"
languageCode = "ja-jp"
title = "Weblog by shuuji3"
# theme
theme = "hugo-now"
# Comment the themesDir option if you use this theme in production
#themesDir = "../.."
# google analytics
GoogleAnalytics = "UA-7053288-5"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Software Engineering"
  author = "TAKAHASHI Shuuji <shuuji3@gmail.com>"
  keywords = ["software-engineering"]
  avatar = "/images/emoji-google-unicorn-face.png"
  displayauthor = false
  # pagination
  paginate = 10
  paginatePath = "page"

[markup]
  [markup.highlight]
    noClasses = false
    style = "pastie"
